preFoil import fix to address #147
mdolab/pygeo pull request #148
Opened 2022-07-29 18:50 UTC by eytanadler

## Purpose

This PR changes the `DVGeometryCST` imports and tests to behave like the other specialized parameterizations. The purpose is to avoid adding prefoil as a dependency even though it is required for `DVGeometryCST` (same idea as `pyOCSM` for `DVGeometryESP`, for example). Addresses #147.

## Expected time until merged

Yesterday

## Type of change

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [ ] Maintenance update
- [ ] Other (please describe)

## Testing

## Checklist

- [ ] I have run `flake8` and `black` to make sure the code adheres to PEP-8 and is consistently formatted
- [ ] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

2022-07-31 00:46 UTC, sseraj requested changes
Thanks for the prompt PR. To get this to work though, this file also has to be changed: https://github.com/mdolab/pygeo/blob/d786ca844e8bb2de82de9ec52ebb7d1ddf3504e5/pygeo/parameterization/__init__.py#L3

2022-07-31 01:49 UTC, eytanadler commented
> Thanks for the prompt PR. To get this to work though, this file also has to be changed:
> 
> https://github.com/mdolab/pygeo/blob/d786ca844e8bb2de82de9ec52ebb7d1ddf3504e5/pygeo/parameterization/__init__.py#L3

Good catch

2022-07-31 02:25 UTC, sseraj submitted a review, later dismissed

2022-08-01 13:45 UTC, marcomangano approved these changes

2022-08-01 14:06 UTC, sseraj approved these changes
@marcomangano Please merge this because I am not a maintainer

2022-08-01 14:09 UTC, merged