Moved OpenVSP version check to fix API docs
mdolab/pygeo pull request #210
Opened 2023-07-14 17:40 UTC by sseraj

## Purpose

#198 broke the API docs for DVGeometryVSP, the modules that follow it in `__init__.py` (DVGeometryESP, DVGeometryMulti), and the MPhys wrapper. The problem is that the `openvsp.GetVSPVersion()` call occurs outside the class, which does not work when we have mock imports for the doc build. To fix this, I moved the version check into the `__init__` function.

## Expected time until merged

1 week

## Type of change

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (non-backwards-compatible fix or feature)
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no API changes)
- [ ] Documentation update
- [x] Maintenance update
- [ ] Other (please describe)

## Testing

Check the API docs for the latest docs build and compare to the PR build. All the API docs should be working on the PR build.

## Checklist

- [x] I have run `flake8` and `black` to make sure the Python code adheres to PEP-8 and is consistently formatted
- [ ] I have formatted the Fortran code with `fprettify` or C/C++ code with `clang-format` as applicable
- [x] I have run unit and regression tests which pass locally with my changes
- [ ] I have added new tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation

2023-07-17 17:25 UTC, hajdik approved these changes
LGTM but @ArshSaja or @lamkina should make sure VSP still works with one of their cases

2023-07-17 17:32 UTC, lamkina requested changes
@sseraj  there is a unit test for the out of date features, but can you expand it to check the different version conditions?  I think the machinery is there to do it fairly easily.

2023-07-20 18:31 UTC, lamkina commented
Okay, I guess it's fine.  We're throwing a descriptive error message about the version so the user will be made aware of the problem.

2023-07-20 18:31 UTC, lamkina approved these changes

2023-07-20 19:08 UTC, merged